-- Run this file in the Supabase SQL Editor. It creates FitCart's schema,
-- security policies, and the transactional order-placement RPC.
create extension if not exists pgcrypto;

create type public.app_role as enum ('customer', 'merchant');
create type public.order_status as enum ('pending', 'confirmed', 'packed', 'shipped', 'delivered', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.app_role not null default 'customer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  original_price numeric(10,2) check (original_price is null or original_price >= price),
  category text not null,
  image text not null,
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete restrict,
  customer_name text not null,
  phone text not null,
  email text not null,
  address text not null,
  city text not null,
  state text not null,
  pincode text not null,
  subtotal numeric(10,2) not null check (subtotal >= 0),
  shipping numeric(10,2) not null check (shipping >= 0),
  total numeric(10,2) not null check (total >= 0),
  payment_method text not null default 'Cash on Delivery',
  status public.order_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price numeric(10,2) not null check (price >= 0),
  quantity integer not null check (quantity > 0)
);

create index products_category_idx on public.products(category);
create index products_active_idx on public.products(is_active);
create index orders_user_created_idx on public.orders(user_id, created_at desc);
create index orders_status_created_idx on public.orders(status, created_at desc);
create index order_items_order_idx on public.order_items(order_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_merchant()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'merchant');
$$;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id and role = 'customer');
create policy "Merchants read profiles" on public.profiles for select using (public.is_merchant());

create policy "Anyone reads active products" on public.products for select using (is_active = true);
create policy "Merchants manage products" on public.products for all using (public.is_merchant()) with check (public.is_merchant());

create policy "Customers read own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Merchants read orders" on public.orders for select using (public.is_merchant());
create policy "Merchants update orders" on public.orders for update using (public.is_merchant()) with check (public.is_merchant());

create policy "Customers read own order items" on public.order_items for select using (
  exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
);
create policy "Merchants read order items" on public.order_items for select using (public.is_merchant());

-- This SECURITY DEFINER function locks each product row before it checks stock,
-- then creates the order and snapshots its item prices in one database transaction.
create or replace function public.place_order(
  p_customer_name text, p_phone text, p_email text, p_address text,
  p_city text, p_state text, p_pincode text, p_items jsonb
)
returns table (id uuid, order_number text, subtotal numeric, shipping numeric, total numeric)
language plpgsql security definer set search_path = public as $$
declare
  v_user_id uuid := auth.uid();
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_subtotal numeric(10,2) := 0;
  v_shipping numeric(10,2);
  v_order_id uuid := gen_random_uuid();
  v_order_number text := 'FC' || to_char(clock_timestamp(), 'YYMMDDHH24MISS') || floor(random() * 900 + 100)::text;
begin
  if v_user_id is null then raise exception 'You must be logged in to place an order'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Your cart is empty'; end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_quantity := (v_item ->> 'quantity')::integer;
    if v_quantity is null or v_quantity < 1 then raise exception 'Invalid item quantity'; end if;
    select * into v_product from public.products where id = (v_item ->> 'productId')::bigint and is_active = true for update;
    if not found then raise exception 'One of the selected products is unavailable'; end if;
    if v_product.stock < v_quantity then raise exception '% has only % left in stock', v_product.name, v_product.stock; end if;
    v_subtotal := v_subtotal + (v_product.price * v_quantity);
  end loop;

  v_shipping := case when v_subtotal >= 999 then 0 else 49 end;
  insert into public.orders (id, order_number, user_id, customer_name, phone, email, address, city, state, pincode, subtotal, shipping, total)
  values (v_order_id, v_order_number, v_user_id, trim(p_customer_name), trim(p_phone), trim(p_email), trim(p_address), trim(p_city), trim(p_state), trim(p_pincode), v_subtotal, v_shipping, v_subtotal + v_shipping);

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_quantity := (v_item ->> 'quantity')::integer;
    select * into v_product from public.products where id = (v_item ->> 'productId')::bigint for update;
    insert into public.order_items (order_id, product_id, product_name, price, quantity)
    values (v_order_id, v_product.id, v_product.name, v_product.price, v_quantity);
    update public.products set stock = stock - v_quantity where id = v_product.id;
  end loop;

  return query select v_order_id, v_order_number, v_subtotal, v_shipping, v_subtotal + v_shipping;
end;
$$;

revoke all on function public.place_order(text, text, text, text, text, text, text, jsonb) from public;
grant execute on function public.place_order(text, text, text, text, text, text, text, jsonb) to authenticated;
